Update input configuration.
EdgePi-Cloud/node-red-edgepi-digital-input pull request #10
Opened 2023-12-22 17:35 UTC by josiah-tesfu

Updated the input configuration. Configuration is initially set through the editor. Once the node is deployed, configuration can be set dynamically from input. If any parameters from the input message are empty, the previously set configurations are used.

2023-12-22 22:19 UTC, maria-mz submitted a review, later dismissed

2023-12-23 00:09 UTC, sjpark608 submitted a review, later dismissed

2023-12-23 00:56 UTC, farzadpanahi submitted a review, later dismissed

2023-12-28 21:13 UTC, jimmy121192 requested changes

2023-12-28 21:13 UTC, jimmy121192 commented on edgepi-digital-input.js
> +    async function initializeNode(config) {
`async` is not being used here.

2023-12-30 02:36 UTC, josiah-tesfu commented on edgepi-digital-input.js
> +    async function initializeNode(config) {
Fixed.

2024-01-09 23:11 UTC, jimmy121192 approved these changes

2024-01-09 23:17 UTC, merged